name: Convertir MDX a HTML

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN_POC_NOTARY_SECRET }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Configurar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9'

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar script de build
        run: pnpm run build

      - name: Publicar cambios en /docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git add docs/scripts/vendor.js
          git add docs/scripts/app.js
          set +e  # Desactiva la detención automática por errores
          git diff --staged --quiet
          CHANGED=$?
          set -e  # La reactiva para el resto del script
          if [ $STATUS -eq 1 ]; then
            git commit -m "chore: actualizar index.html generado"
            git push
          fi
          echo "Status $CHANGED"
